import { Bundle } from "#model/Bundle.js";

export const FlightCompanionBundle: Bundle = {
  outputs: [
    {
      category: "Engines",
      cb_text: "Throttle lower limit",
      id: 655,
      metric: "Percent Over 100",
      output_type: "Percentage",
      selected: true,
      simvar: "THROTTLE LOWER LIMIT",
      update_every: 0.01,
    },
    {
      category: "Instruments",
      cb_text: "Indicated altitude",
      id: 335,
      metric: "Feet",
      output_type: "Integer",
      selected: true,
      simvar: "INDICATED ALTITUDE",
      update_every: 10,
    },
    {
      category: "Fuel",
      cb_text: "Fuel quantity %",
      id: 275,
      metric: "Percent Over 100",
      output_type: "Percentage",
      selected: true,
      simvar: "FUEL SELECTED QUANTITY PERCENT",
      update_every: 0.01,
    },
    {
      category: "Instruments",
      cb_text: "Indicated heading",
      id: 344,
      metric: "Radians",
      output_type: "Degrees",
      selected: true,
      simvar: "HEADING INDICATOR",
      update_every: 0.02,
    },
    {
      category: "NAV and COMS",
      cb_text: "Com 1 active",
      id: 900,
      metric: "Khz",
      output_type: "Integer",
      selected: true,
      simvar: "COM ACTIVE FREQUENCY:1",
      update_every: 0,
    },
    {
      category: "Fuel",
      cb_text: "Fuel tank left main level",
      id: 237,
      metric: "Percent Over 100",
      output_type: "Percentage",
      selected: true,
      simvar: "FUEL TANK LEFT MAIN LEVEL",
      update_every: 0.01,
    },
    {
      category: "Fuel",
      cb_text: "AP airspeed var",
      id: 700,
      metric: "knots",
      output_type: "Integer",
      selected: true,
      simvar: "AUTOPILOT AIRSPEED HOLD VAR",
      update_every: 0,
    },
    {
      category: "Autopilot",
      cb_text: "AP heading lock",
      id: 582,
      metric: "Degrees",
      output_type: "Integer",
      selected: true,
      simvar: "AUTOPILOT HEADING LOCK DIR",
      update_every: 0,
    },
    {
      category: "NAV and COMS",
      cb_text: "Com 2 active",
      id: 902,
      metric: "Khz",
      output_type: "Integer",
      selected: true,
      simvar: "COM ACTIVE FREQUENCY:2",
      update_every: 0,
    },
    {
      category: "NAV and COMS",
      cb_text: "Com 1 standby",
      id: 901,
      metric: "Khz",
      output_type: "Integer",
      selected: true,
      simvar: "COM STANDBY FREQUENCY:1",
      update_every: 0,
    },
    {
      category: "Autopilot",
      cb_text: "AP altitude lock var",
      id: 584,
      metric: "Feet",
      output_type: "Integer",
      selected: true,
      simvar: "AUTOPILOT ALTITUDE LOCK VAR",
      update_every: 0,
    },
    {
      category: "Environment",
      cb_text: "Ambient precipitation rate",
      id: 654,
      metric: "millimeters of water",
      output_type: "Integer",
      selected: true,
      simvar: "AMBIENT PRECIP RATE",
      update_every: 1,
    },
    {
      category: "Autopilot",
      cb_text: "(bool) AP available",
      id: 576,
      metric: "Bool",
      output_type: "Boolean",
      selected: true,
      simvar: "AUTOPILOT AVAILABLE",
      update_every: 0,
    },
    {
      category: "NAV and COMS",
      cb_text: "NAV 1 active",
      id: 910,
      metric: "KHz",
      output_type: "Integer",
      selected: true,
      simvar: "NAV ACTIVE FREQUENCY:1",
      update_every: 0,
    },
    {
      category: "Autopilot",
      cb_text: "(bool) AP vertical hold",
      id: 604,
      metric: "Bool",
      output_type: "Boolean",
      selected: true,
      simvar: "AUTOPILOT VERTICAL HOLD",
      update_every: 0,
    },
    {
      category: "Autopilot",
      cb_text: "AP vertical hold var",
      id: 590,
      metric: "Feet/minute",
      output_type: "Integer",
      selected: true,
      simvar: "AUTOPILOT VERTICAL HOLD VAR",
      update_every: 0,
    },
    {
      category: "NAV and COMS",
      cb_text: "NAV 2 standby",
      id: 913,
      metric: "KHz",
      output_type: "Integer",
      selected: true,
      simvar: "NAV STANDBY FREQUENCY:2",
      update_every: 0,
    },
    {
      category: "Fuel",
      cb_text: "Fuel tank center 3 level",
      id: 236,
      metric: "Percent Over 100",
      output_type: "Percentage",
      selected: true,
      simvar: "FUEL TANK CENTER3 LEVEL",
      update_every: 0.01,
    },
    {
      category: "Fuel",
      cb_text: "Fuel tank center level",
      id: 234,
      metric: "Percent Over 100",
      output_type: "Percentage",
      selected: true,
      simvar: "FUEL TANK CENTER LEVEL",
      update_every: 0.01,
    },
    {
      category: "Fuel",
      cb_text: "Fuel tank center 2 level",
      id: 235,
      metric: "Percent Over 100",
      output_type: "Percentage",
      selected: true,
      simvar: "FUEL TANK CENTER2 LEVEL",
      update_every: 0.01,
    },
    {
      category: "Autopilot",
      cb_text: "(bool) AP altitude lock",
      id: 583,
      metric: "Bool",
      output_type: "Boolean",
      selected: true,
      simvar: "AUTOPILOT ALTITUDE LOCK",
      update_every: 0,
    },
    {
      category: "Autopilot",
      cb_text: "(bool) AP master",
      id: 577,
      metric: "Bool",
      output_type: "Boolean",
      selected: true,
      simvar: "AUTOPILOT MASTER",
      update_every: 0,
    },
    {
      category: "NAV and COMS",
      cb_text: "NAV 1 standby",
      id: 911,
      metric: "KHz",
      output_type: "Integer",
      selected: true,
      simvar: "NAV STANDBY FREQUENCY:1",
      update_every: 0,
    },
    {
      category: "NAV and COMS",
      cb_text: "Com 2 standby",
      id: 903,
      metric: "Khz",
      output_type: "Integer",
      selected: true,
      simvar: "COM STANDBY FREQUENCY:2",
      update_every: 0,
    },
    {
      category: "NAV and COMS",
      cb_text: "NAV 2 active",
      id: 912,
      metric: "KHz",
      output_type: "Integer",
      selected: true,
      simvar: "NAV ACTIVE FREQUENCY:2",
      update_every: 0,
    },
    {
      category: "Autopilot",
      cb_text: "(bool) AP heading lock",
      id: 581,
      metric: "Bool",
      output_type: "Boolean",
      selected: true,
      simvar: "AUTOPILOT HEADING LOCK",
      update_every: 0,
    },
  ],
  name: "",
  version: 0,
};
